kind: icon_aggregate
config:
  repo_root: "."
  lsdf_base: /Volumes/iip-projects/energy/climateData/icon_by_Max_Kleinebrahm
  output_parent: data/processed/icon_aggregated_c2_run00
  shapefile_path: data/shapefile/ne_10m_admin_0_countries.shp
  cluster_output_file: data/clustering/icon_d2_clustering_c2_run00.parquet
  n_clusters: 2
  buffer_km: 50
  plot_clusters: false
  skip_existing_output: true
  only_day: null
  only_run_hour: "00"
  start_date: "2025-10-25"
  variables:
    - u_10m
    - v_10m
    - aswdir_s
    - aswdifd_s
